name: Sync to Gitee

on:
  push:
    branches:
      - main

jobs:
  repo-sync:
    env:
      dst_token: ${{ secrets.GITEE_TOKEN }}
      gitee_user: ${{ secrets.GITEE_USER }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v2

      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/${{ github.repository_owner }}
          dst: gitee/${{ secrets.GITEE_USER }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: '${{ github.event.repository.name }}'
          force_update: true
          debug: true
